# -*- coding: utf-8 -*-
"""Model_Performance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z4O0HPtN1HIC8497DWA0CVUgEKjXUBlx
"""

import streamlit as st
import pickle
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, roc_curve, precision_recall_curve, auc

st.set_page_config(page_title="Model Performance", page_icon="📈")
st.title("📈 মডেল পারফরম্যান্স এবং ব্যাখ্যা")
st.write("এই পেইজে আমরা দেখবো আমাদের XGBoost মডেলটি पर्दे के पीछे কীভাবে কাজ করছে।")

# --- প্রয়োজনীয় ফাইল লোড করা ---
@st.cache_data
def load_assets():
    try:
        with open('fraud_detection_model.pkl', 'rb') as f:
            model = pickle.load(f)
        with open('test_data.pkl', 'rb') as f:
            test_data = pickle.load(f)
        with open('feature_names.pkl', 'rb') as f:
            feature_names = pickle.load(f)

        X_test = test_data['X_test']
        y_test = test_data['y_test']
        return model, X_test, y_test, feature_names
    except FileNotFoundError:
        st.error("প্রয়োজনীয় ফাইল (.pkl) পাওয়া যায়নি। GitHub-এ সব ফাইল আপলোড হয়েছে কিনা দেখুন।")
        return None, None, None, None

model, X_test, y_test, feature_names = load_assets()

if model:
    # --- মডেলের প্রেডিকশন তৈরি করা ---
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1] # ফ্রড হওয়ার সম্ভাবনা

    # --- ১. ফিচার ইম্পর্ট্যান্স (Feature Importance) ---
    st.header("১. ফিচার ইম্পর্ট্যান্স (Model Explainability)")
    st.write("মডেলটি কোন বিষয়গুলোকে সবচেয়ে বেশি গুরুত্ব দিয়ে 'ফ্রড' শনাক্ত করছে?")

    try:
        importance = model.feature_importances_
        feature_importance_df = pd.DataFrame({
            'Feature': feature_names,
            'Importance': importance
        }).sort_values(by='Importance', ascending=False)

        # সেরা ১০টি ফিচার দেখানো
        fig_imp, ax_imp = plt.subplots(figsize=(10, 6))
        sns.barplot(x='Importance', y='Feature', data=feature_importance_df.head(10), ax=ax_imp)
        ax_imp.set_title("টপ ১০টি গুরুত্বপূর্ণ ফিচার", fontsize=16)
        st.pyplot(fig_imp)

    except Exception as e:
        st.warning(f"ফিচার ইম্পর্ট্যান্স চার্ট লোড করা যায়নি: {e}")


    # --- ২. কনফিউশন ম্যাট্রিক্স (Confusion Matrix) ---
    st.header("২. কনফিউশন ম্যাট্রিক্স")
    st.write("মডেলটি কতগুলো প্রেডিকশন সঠিক এবং কতগুলো ভুল করেছে তার বিস্তারিত।")

    cm = confusion_matrix(y_test, y_pred)
    fig_cm, ax_cm = plt.subplots(figsize=(7, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Normal', 'Fraud'],
                yticklabels=['Normal', 'Fraud'], ax=ax_cm)
    ax_cm.set_xlabel("প্রেডিক্টেড ক্লাস")
    ax_cm.set_ylabel("আসল ক্লাস")
    ax_cm.set_title("Confusion Matrix", fontsize=16)
    st.pyplot(fig_cm)

    st.info(f"""
    * **True Positive (TP):** {cm[1][1]} টি ফ্রড কেস সঠিকভাবে ধরেছে।
    * **False Negative (FN):** {cm[1][0]} টি ফ্রড কেস ধরতে **ব্যর্থ** হয়েছে। (এটিই সবচেয়ে ক্ষতিকর!)
    * **False Positive (FP):** {cm[0][1]} টি স্বাভাবিক কেসকে ভুলবশত 'ফ্রড' বলেছে।
    """)

    # --- ৩. ROC এবং Precision-Recall কার্ভ ---
    st.header("৩. অ্যাডভান্সড পারফরম্যান্স কার্ভ")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("ROC Curve")
        fpr, tpr, _ = roc_curve(y_test, y_proba)
        roc_auc = auc(fpr, tpr)

        fig_roc, ax_roc = plt.subplots()
        ax_roc.plot(fpr, tpr, label=f'AUC = {roc_auc:.2f}')
        ax_roc.plot([0, 1], [0, 1], 'k--') # Random guess line
        ax_roc.set_xlabel('False Positive Rate')
        ax_roc.set_ylabel('True Positive Rate')
        ax_roc.set_title('Receiver Operating Characteristic')
        ax_roc.legend(loc='lower right')
        st.pyplot(fig_roc)

    with col2:
        st.subheader("Precision-Recall Curve")
        precision, recall, _ = precision_recall_curve(y_test, y_proba)
        pr_auc = auc(recall, precision)

        fig_pr, ax_pr = plt.subplots()
        ax_pr.plot(recall, precision, label=f'AUC = {pr_auc:.2f}')
        ax_pr.set_xlabel('Recall')
        ax_pr.set_ylabel('Precision')
        ax_pr.set_title('Precision-Recall Curve')
        ax_pr.legend(loc='lower left')
        st.pyplot(fig_pr)

    st.markdown("""
    **কীভাবে এই চার্টগুলো পড়বেন:**
    * **ROC Curve:** চার্টটি যত উপরের-বাম কোণার কাছাকাছি যাবে, মডেল তত ভালো।
    * **Precision-Recall Curve:** এই ধরনের ইমব্যালান্সড ডেটাসেটের জন্য এটি বেশি গুরুত্বপূর্ণ। চার্টটি যত উপরের-ডান কোণার কাছাকাছি যাবে, মডেল তত ভালো।
    """)

else:
    st.error("অ্যাপটি লোড করার জন্য প্রয়োজনীয় ফাইল পাওয়া যায়নি।")